language: python
dist: xenial
python:
    - 3.6
    - 3.7
install:
    - pip install pytest coverage coveralls
script:
    - coverage run -m pytest tests.py
    - coverage report
after_script:
    - coveralls
notifications:
    email: false
