language: python
dist: xenial
python:
    - 3.6
    - 3.7
install:
    - pip install pytest coverage coveralls flake8
script:
    - coverage run -m pytest tests.py
    - coverage report
    - flake8 *.py
after_script:
    - coveralls
notifications:
    email: false
